document.write('\
	<style type="text/css">\
	.editorBtn {width: 22px; height: 22px; border: 1px solid #ECE9D8; background-color:#ECE9D8; opacity: 1;}\
	.btnOver {width: 22px; height: 22px; border: 1px solid #316AC5; background-color: #C1D2EE; opacity: 1;}\
	.btnDown {width: 22px; height: 22px; border: 1px solid #316AC5; background-color: #98B5E2; opacity: 1;}\
	.btnSelected {width: 22px; height: 22px; border: 1px solid #316AC5; background-color: #E1E6E8; opacity: 1;}\
	.btnNA {width: 22px; height: 22px; border: 1px solid #ECE9D8; background-color: #ECE9D8; opacity: .25;}\
	.image {position: relative; left: 1; top: 1; height:18; width:18; border:none;}\
	</style>\
');var command;var contextbuttons={"bold":false,"italic":false,"underline":false,"justifyleft":false,"justifycenter":false,"justifyright":false,"insertorderedlist":false,"insertunorderedlist":false};var oTextarea;var htmlFrame;var htmlWindow;var htmlEditor;function toggleToolbarButtons(enable){var kids=document.getElementsByTagName('DIV');for(var i=0;i<kids.length;i++){if(kids[i].className.match(/^editorBtn/)){if(enable){kids[i].onmouseover=tbmouseover;kids[i].onmouseout=tbmouseout;kids[i].onmousedown=tbmousedown;kids[i].onmouseup=tbmouseup;kids[i].onclick=tbclick;kids[i].className="editorBtn";}else{if(kids[i].id=='viewsource')continue;kids[i].onmouseover=null;kids[i].onmouseout=null;kids[i].onmousedown=null;kids[i].onmouseup=null;kids[i].onclick=null;kids[i].className="btnNA";}}}
var ddFontname=document.getElementById('fontname');var ddFontsize=document.getElementById('fontsize');if(enable){ddFontname.style.opacity=1;ddFontname.disabled=false;ddFontsize.style.opacity=1;ddFontsize.disabled=false;}else{ddFontname.style.opacity=.25;ddFontname.disabled=true;ddFontsize.style.opacity=.25;ddFontsize.disabled=true;}}
function tbmousedown(e){this.firstChild.style.left=2;this.firstChild.style.top=2;e.preventDefault();}
function tbmouseup(){this.firstChild.style.left=1;this.firstChild.style.top=1;}
function tbmouseout(){if(this.className=='btnOver')this.className="editorBtn";}
function tbmouseover(){if(this.className=='editorBtn')this.className="btnOver";}
function insertNodeAtSelection(node){var lastNode;var sel=htmlWindow.getSelection();var range=sel.getRangeAt(0);sel.removeAllRanges();range.deleteContents();var container=range.startContainer;var iOffSet=range.startOffset;var range=htmlEditor.createRange();range.setStart(container,iOffSet);range.setEnd(container,iOffSet);if(!node.nodeType)node=range.createContextualFragment(node);if(node.lastChild)lastNode=node.lastChild;else
lastNode=node;range.insertNode(node);range.setEndAfter(lastNode);range.setStartAfter(lastNode);sel.removeAllRanges();sel=htmlWindow.getSelection();sel.addRange(range);}
function tbclick(){if((this.id=="forecolor")||(this.id=="hilitecolor")){command=this.id;var buttonElement=document.getElementById(this.id);var oPalette=document.getElementById("colorpalette");oPalette.style.left=getOffsetLeft(buttonElement);oPalette.style.top=getOffsetTop(buttonElement)+buttonElement.offsetHeight;oPalette.style.display="";}else if(this.id=="createlink"){var sel=htmlWindow.getSelection();if(sel==''||sel==null){alert("Your browser requires that you must select some text for this function to work.");return;}
var szURL=prompt("Please enter the URL of your link:","http://");if(szURL!=null&&szURL!=""&&szURL!="http://"){htmlEditor.execCommand("CreateLink",false,szURL);}else{htmlEditor.execCommand("UnLink",false,null);}}else if(this.id=="createimage"){var imagePath=prompt('Please enter the URL of your image:','http://');if(imagePath!=null&&imagePath!=""&&szURL!="http://"){htmlEditor.execCommand('InsertImage',false,imagePath);}}else if(this.id=="createtable"){var rowstext=prompt("Please enter the number of rows:");var colstext=prompt("Please enter the number of columns:");var rows=parseInt(rowstext);var cols=parseInt(colstext);if(rows>0&&cols>0){var table=htmlEditor.createElement("table");table.setAttribute("border","1");table.setAttribute("cellpadding","2");table.setAttribute("cellspacing","2");var tbody=htmlEditor.createElement("tbody");for(var i=0;i<rows;i++){var tr=htmlEditor.createElement("tr");var td;for(var j=0;j<cols;j++){td=htmlEditor.createElement("td");td.appendChild(htmlEditor.createElement("br"));tr.appendChild(td);}
tbody.appendChild(tr);}
table.appendChild(tbody);insertNodeAtSelection(table);}else{alert("Error: You entered an invalid number of rows or columns.");}}else if(this.id=='createhr'){insertNodeAtSelection('<hr>');}else if(this.id=='code'){htmlEditor.execCommand('removeformat',false,null);wrapTags('CODE');}else if(this.id=='quote'){wrapTags('QUOTE');}else if(this.id=='smilie'){smilieWindow();}else if(this.id=='viewsource'){viewsource(!(document.getElementById('fontname').disabled));}else{try{htmlEditor.execCommand(this.id,false,null);updateToolbarContext();}catch(e){var keyboard_shortcut;if(this.id=="cut"){keyboard_shortcut="Ctl+X";}else if(this.id=="copy"){keyboard_shortcut="Ctl+C";}else if(this.id=="paste"){keyboard_shortcut="Ctl+V";}
if(keyboard_shortcut){alert("Your browser has restricted this action due to security reasons. Please edit your browser configuration file to allow this action or use the "+keyboard_shortcut+" keys on your keyboard instead.");}}}}
function Select(selectname){var cursel=document.getElementById(selectname).selectedIndex;if(cursel!=0){var selected=document.getElementById(selectname).options[cursel].value;htmlEditor.execCommand(selectname,false,selected);document.getElementById(selectname).selectedIndex=0;}
htmlWindow.focus();updateToolbarContext();}
function updateToolbarContext(){for(var editorBtn in contextbuttons){var qcs=htmlEditor.queryCommandState(editorBtn);if(contextbuttons[editorBtn]!=qcs){if(qcs==true){document.getElementById(editorBtn).className="btnSelected";}else{document.getElementById(editorBtn).className="editorBtn";}
contextbuttons[editorBtn]=qcs;}}
var fontname=htmlEditor.queryCommandValue("fontname");var oFontname=document.getElementById('fontname');if(fontname==null||fontname==''){oFontname.selectedIndex=0;}else{var found=0;for(i=0;i<oFontname.length;i++){if(fontname.toLowerCase()==oFontname[i].text.toLowerCase()){oFontname.selectedIndex=i;found=1;}}
if(found!=1){oFontname.selectedIndex=0;}}
var fontsize=htmlEditor.queryCommandValue("fontsize");var oFontsize=document.getElementById('fontsize');if(fontsize==null||fontsize==''){oFontsize.selectedIndex=0;}else{var found=0;for(i=0;i<oFontsize.length;i++){if(fontsize.toLowerCase()==oFontsize[i].text.toLowerCase()){oFontsize.selectedIndex=i;found=1;}}
if(found!=1){oFontsize.selectedIndex=0;}}}
function startEditor(myTextarea){oTextarea=myTextarea;try{document.getElementById('toolbar').style.display="";htmlFrame=document.getElementById('edit');htmlWindow=htmlFrame.contentWindow;htmlEditor=htmlWindow.document;htmlEditor.designMode="on";htmlEditor.execCommand("undo",false,null);}catch(e){htmlFrame.style.display="none";document.getElementById('toolbar').style.display="none";return;}
oTextarea.style.display="none";if(oTextarea.form.adv_toolbar)oTextarea.form.adv_toolbar.value=1;if(oTextarea.value){oTextarea.value=oTextarea.value.replace(/\r\n/g,'<br>').replace(/\n/g,'<br>').replace(/\r/g,'<br>');htmlEditor.body.innerHTML=oTextarea.value;}
toggleToolbarButtons(1);htmlEditor.execCommand("useCSS",false,true);oTextarea.form.addEventListener("submit",finishEditor,true);document.addEventListener("mousedown",dismisscolorpalette,true);document.addEventListener("keypress",dismisscolorpalette,true);htmlEditor.addEventListener("mousedown",dismisscolorpalette,true);htmlEditor.addEventListener("keypress",dismisscolorpalette,true);htmlEditor.addEventListener("keypress",checkTabKey,true);htmlEditor.addEventListener("mouseup",updateToolbarContext,true);htmlEditor.addEventListener("keyup",updateToolbarContext,true);if(oTextarea.form.subject)oTextarea.form.subject.addEventListener("keypress",fixTabindex,true);}
function finishEditor(e){var links=htmlEditor.getElementsByTagName("a");for(var i=0;i<links.length;i++){links[i].setAttribute("target","_blank");}
oTextarea.value=htmlEditor.body.innerHTML;oTextarea.value=oTextarea.value.replace(/\n|\r/g,' ');oTextarea.value=oTextarea.value.replace(/<\?xml:[^>]*>/g,'').replace(/<\/?st1:[^>]*>/g,'').replace(/<\/?[a-z]\:[^>]*>/g,'');oTextarea.value=oTextarea.value.replace(/\[CODE\]/g,"[code]").replace(/\[\/CODE\]/g,"[/code]");while((innerCodeArray=oTextarea.value.match(/\[code\]([\s\S]+?)\[\/code\]/))!=null){var innerCode=innerCodeArray[1];innerCode=innerCode.replace(/<br>/ig,"\r\n").replace(/<[\s\S]+?>/g,"").replace(/\&nbsp\;/g," ");oTextarea.value=oTextarea.value.replace("[code]"+innerCodeArray[1]+"[/code]","[CODE]"+innerCode+"[/CODE]");}}
function viewsource(source){var html;if(source){html=document.createTextNode(htmlEditor.body.innerHTML);htmlEditor.body.innerHTML="";htmlEditor.body.appendChild(html);toggleToolbarButtons(0);}else{html=htmlEditor.body.ownerDocument.createRange();html.selectNodeContents(htmlEditor.body);htmlEditor.body.innerHTML=html.toString();toggleToolbarButtons(1);}}
function wrapTags(tag){var sel=htmlWindow.getSelection();var range=sel.getRangeAt(0);var clone=range.cloneContents();var frag=htmlEditor.createDocumentFragment();frag.appendChild(range.createContextualFragment("["+tag+"]"));while(clone.firstChild){frag.appendChild(clone.firstChild);}
frag.appendChild(range.createContextualFragment("[/"+tag+"]"));insertNodeAtSelection(frag);}
function fixTabindex(e){if(e.keyCode==9){e.preventDefault();e.stopPropagation();htmlWindow.focus();}}
function dismisscolorpalette(){document.getElementById("colorpalette").style.display="none";}
function checkTabKey(e){if(e.keyCode==9){if(oTextarea.form.submitbutton){oTextarea.form.submitbutton.focus();}else if(oTextarea.form.add&&oTextarea.form.add.type=='submit'){oTextarea.form.add.focus();}else if(oTextarea.form.submit&&oTextarea.form.submit.type=='submit'){oTextarea.form.submit.focus();}else if(document.getElementById('imageField')&&document.getElementById('imageField').type=='image'&&document.getElementById('imageField').form==oTextarea.form){document.getElementById('imageField').focus();}else{return;}
e.preventDefault();}}
function getOffsetTop(elm){var mOffsetTop=elm.offsetTop;var mOffsetParent=elm.offsetParent;while(mOffsetParent){mOffsetTop+=mOffsetParent.offsetTop;mOffsetParent=mOffsetParent.offsetParent;}
return mOffsetTop;}
function getOffsetLeft(elm){var mOffsetLeft=elm.offsetLeft;var mOffsetParent=elm.offsetParent;while(mOffsetParent){mOffsetLeft+=mOffsetParent.offsetLeft;mOffsetParent=mOffsetParent.offsetParent;}
return mOffsetLeft;}